export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'

export const CHECK_AUTH_REQUEST = 'CHECK_AUTH_REQUEST'
export const CHECK_AUTH_SUCCESS = 'CHECK_AUTH_SUCCESS'
export const CHECK_AUTH_FAILURE = 'CHECK_AUTH_FAILURE'

export const COMPONENTS_REQUEST = 'COMPONENTS_REQUEST'
export const COMPONENTS_SUCCESS = 'COMPONENTS_SUCCESS'
export const COMPONENTS_FAILURE = 'COMPONENTS_FAILURE'

export const CHANGE_AUDIO_SWITCH_REQUEST = 'CHANGE_AUDIO_SWITCH_REQUEST'
export const CHANGE_AUDIO_SWITCH_SUCCESS = 'CHANGE_AUDIO_SWITCH_SUCCESS'
export const CHANGE_AUDIO_SWITCH_FAILURE = 'CHANGE_AUDIO_SWITCH_FAILURE'

export const CHANGE_DIMMER_REQUEST = 'CHANGE_DIMMER_REQUEST'
export const CHANGE_DIMMER_SUCCESS = 'CHANGE_DIMMER_SUCCESS'
export const CHANGE_DIMMER_FAILURE = 'CHANGE_DIMMER_FAILURE'

export const CHANGE_SOCKET_REQUEST = 'CHANGE_SOCKET_REQUEST'
export const CHANGE_SOCKET_SUCCESS = 'CHANGE_SOCKET_SUCCESS'
export const CHANGE_SOCKET_FAILURE = 'CHANGE_SOCKET_FAILURE'


export const UP_BLIND_REQUEST = 'UP_BLIND_REQUEST'
export const UP_BLIND_SUCCESS = 'UP_BLIND_SUCCESS'
export const UP_BLIND_FAILURE = 'UP_BLIND_FAILURE'

export const DOWN_BLIND_REQUEST = 'DOWN_BLIND_REQUEST'
export const DOWN_BLIND_SUCCESS = 'DOWN_BLIND_SUCCESS'
export const DOWN_BLIND_FAILURE = 'DOWN_BLIND_FAILURE'


export const REQUEST_OPEN_DRAWER = 'REQUEST_OPEN_DRAWER'
export const REQUEST_CLOSE_DRAWER = 'REQUEST_CLOSE_DRAWER'
export const RESET_EXECUTE_DRAWERS = 'RESET_EXECUTE_DRAWERS'
